### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ViTuDia** [mlava/sidebar-separators#1]
Nice plug-in! Thanks. Was waiting for this. 

Would be nice to have the possibility to have more separators. 

As well it would be nice to have the option the give it a specific color (it is not that good visible in my theme).

**Comment by mlava** [comment]
Thanks @ViTuDia 
https://github.com/Roam-Research/roam-depot/pull/605
I have added two more.
Also, you can now define colour, alignment and width for HR.
Cheers!

**Comment by mlava** [comment]
This update is now live. Let me know if there are other things you want to see implemented. @ViTuDia
