### ISSUE TITLE
Can you add 5 more Separators So I got 10 Available 

### ISSUE THREAD

**Issue by LuciferIsSatan** [mlava/sidebar-separators#2]
I need 5 more additional Separators. Is it possible to add 5 more?

**Comment by mlava** [comment]
https://github.com/Roam-Research/roam-depot/pull/790

This is implemented in this pull request.

**Comment by mlava** [comment]
@LuciferIsSatan this update is now live

**Comment by LuciferIsSatan** [comment]
-

> @LuciferIsSatan this update is now live

Thank you!
